### ISSUE TITLE
Trainer Hub Page for Registered Instructor

### ISSUE THREAD

**Issue by HeshamHassan** [camelcasetechsd/skillsbuilder#182] opened 2018-08-29 12:06 UTC
**URL:** http://skillsbuilderpro.com/Training/Trainer's_hub
**Path:** SBP Home> Training> Trainer Hub
**Subject:**
At the end of Trainer Hub page, there is a link: “Apply Now” which redirect me to the new registration form. When I login as an instructor:
- [ ] The link “Apply Now” must not appear. 
Or, at least redirect to the instructor profile, not the new registration form.

**Comment by HeshamHassan** [comment] 2018-09-09 08:54
**@ahmedelbougha** 
Any update?

**Comment by ahmedelbougha** [comment] 2018-10-02 07:15
@HeshamHassan @Ali-Galal 
This is duplicate of #183, please close it.

**Comment by ahmedelbougha** [comment] 2018-10-04 09:52
@HeshamHassan @Ali-Galal 
Please close this issue as it's a duplicate

**Closed as completed** 2018-10-04 11:11 UTC
